# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'WinBg.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGroupBox,
    QLabel, QLineEdit, QPushButton, QRadioButton,
    QSizePolicy, QSpinBox, QSplitter, QStackedWidget,
    QWidget)

class Ui_form(object):
    def setupUi(self, form):
        if not form.objectName():
            form.setObjectName(u"form")
        form.resize(1008, 554)
        form.setAutoFillBackground(False)
        self.groupBox = QGroupBox(form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(30, 20, 521, 81))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(330, 10, 111, 31))
        font1 = QFont()
        font1.setFamilies([u"\u534e\u5eb7POP"])
        font1.setPointSize(16)
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(80, 10, 111, 31))
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignCenter)
        self.pButSwapTeam = QPushButton(self.groupBox)
        self.pButSwapTeam.setObjectName(u"pButSwapTeam")
        self.pButSwapTeam.setGeometry(QRect(225, 30, 75, 24))
        self.lEdtSur = QLineEdit(self.groupBox)
        self.lEdtSur.setObjectName(u"lEdtSur")
        self.lEdtSur.setGeometry(QRect(80, 40, 113, 21))
        self.lEdtHun = QLineEdit(self.groupBox)
        self.lEdtHun.setObjectName(u"lEdtHun")
        self.lEdtHun.setGeometry(QRect(330, 40, 113, 21))
        self.groupBox_2 = QGroupBox(form)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(570, 20, 271, 81))
        self.groupBox_2.setFont(font)
        self.cBoxMap = QComboBox(self.groupBox_2)
        self.cBoxMap.setObjectName(u"cBoxMap")
        self.cBoxMap.setGeometry(QRect(40, 34, 191, 31))
        self.cBoxMap.setEditable(True)
        self.groupBox_3 = QGroupBox(form)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(30, 110, 381, 251))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(10)
        font2.setBold(False)
        self.groupBox_3.setFont(font2)
        self.cBoxSurBan1 = QComboBox(self.groupBox_3)
        self.cBoxSurBan1.setObjectName(u"cBoxSurBan1")
        self.cBoxSurBan1.setGeometry(QRect(20, 40, 71, 22))
        self.cBoxSurBan1.setEditable(True)
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 20, 54, 16))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.labSurBan1Pic = QLabel(self.groupBox_3)
        self.labSurBan1Pic.setObjectName(u"labSurBan1Pic")
        self.labSurBan1Pic.setGeometry(QRect(30, 70, 51, 51))
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(110, 20, 54, 16))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.cBoxSurBan2 = QComboBox(self.groupBox_3)
        self.cBoxSurBan2.setObjectName(u"cBoxSurBan2")
        self.cBoxSurBan2.setGeometry(QRect(100, 40, 71, 22))
        self.cBoxSurBan2.setEditable(True)
        self.labSurBan2Pic = QLabel(self.groupBox_3)
        self.labSurBan2Pic.setObjectName(u"labSurBan2Pic")
        self.labSurBan2Pic.setGeometry(QRect(109, 70, 51, 51))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(190, 20, 54, 16))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.cBoxSurBan3 = QComboBox(self.groupBox_3)
        self.cBoxSurBan3.setObjectName(u"cBoxSurBan3")
        self.cBoxSurBan3.setGeometry(QRect(180, 40, 71, 22))
        self.cBoxSurBan3.setEditable(True)
        self.labSurBan3Pic = QLabel(self.groupBox_3)
        self.labSurBan3Pic.setObjectName(u"labSurBan3Pic")
        self.labSurBan3Pic.setGeometry(QRect(189, 70, 51, 51))
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(270, 20, 54, 16))
        self.label_6.setAlignment(Qt.AlignCenter)
        self.cBoxSurBan4 = QComboBox(self.groupBox_3)
        self.cBoxSurBan4.setObjectName(u"cBoxSurBan4")
        self.cBoxSurBan4.setGeometry(QRect(260, 40, 71, 22))
        self.cBoxSurBan4.setEditable(True)
        self.labSurBan4Pic = QLabel(self.groupBox_3)
        self.labSurBan4Pic.setObjectName(u"labSurBan4Pic")
        self.labSurBan4Pic.setGeometry(QRect(269, 70, 51, 51))
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 130, 54, 16))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.cBoxSurBan5 = QComboBox(self.groupBox_3)
        self.cBoxSurBan5.setObjectName(u"cBoxSurBan5")
        self.cBoxSurBan5.setGeometry(QRect(20, 150, 71, 22))
        self.cBoxSurBan5.setEditable(True)
        self.labSurBan5Pic = QLabel(self.groupBox_3)
        self.labSurBan5Pic.setObjectName(u"labSurBan5Pic")
        self.labSurBan5Pic.setGeometry(QRect(30, 180, 51, 51))
        self.cBoxSurBan6 = QComboBox(self.groupBox_3)
        self.cBoxSurBan6.setObjectName(u"cBoxSurBan6")
        self.cBoxSurBan6.setGeometry(QRect(100, 150, 71, 22))
        self.cBoxSurBan6.setEditable(True)
        self.label_17 = QLabel(self.groupBox_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(110, 130, 54, 16))
        self.label_17.setAlignment(Qt.AlignCenter)
        self.labSurBan6Pic = QLabel(self.groupBox_3)
        self.labSurBan6Pic.setObjectName(u"labSurBan6Pic")
        self.labSurBan6Pic.setGeometry(QRect(110, 180, 51, 51))
        self.label_34 = QLabel(self.groupBox_3)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(190, 130, 54, 16))
        self.label_34.setAlignment(Qt.AlignCenter)
        self.cBoxSurBan7 = QComboBox(self.groupBox_3)
        self.cBoxSurBan7.setObjectName(u"cBoxSurBan7")
        self.cBoxSurBan7.setGeometry(QRect(180, 150, 71, 22))
        self.cBoxSurBan7.setEditable(True)
        self.labSurBan7Pic = QLabel(self.groupBox_3)
        self.labSurBan7Pic.setObjectName(u"labSurBan7Pic")
        self.labSurBan7Pic.setGeometry(QRect(190, 180, 51, 51))
        self.groupBox_4 = QGroupBox(form)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(430, 110, 181, 251))
        self.groupBox_4.setFont(font)
        self.cBoxHunBan1 = QComboBox(self.groupBox_4)
        self.cBoxHunBan1.setObjectName(u"cBoxHunBan1")
        self.cBoxHunBan1.setGeometry(QRect(20, 40, 71, 22))
        self.cBoxHunBan1.setEditable(True)
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 20, 54, 16))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.labHunBan1Pic = QLabel(self.groupBox_4)
        self.labHunBan1Pic.setObjectName(u"labHunBan1Pic")
        self.labHunBan1Pic.setGeometry(QRect(30, 70, 51, 51))
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(110, 20, 54, 16))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.cBoxHunBan2 = QComboBox(self.groupBox_4)
        self.cBoxHunBan2.setObjectName(u"cBoxHunBan2")
        self.cBoxHunBan2.setGeometry(QRect(100, 40, 71, 22))
        self.cBoxHunBan2.setEditable(True)
        self.labHunBan2Pic = QLabel(self.groupBox_4)
        self.labHunBan2Pic.setObjectName(u"labHunBan2Pic")
        self.labHunBan2Pic.setGeometry(QRect(110, 70, 51, 51))
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 130, 54, 16))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.cBoxHunBan3 = QComboBox(self.groupBox_4)
        self.cBoxHunBan3.setObjectName(u"cBoxHunBan3")
        self.cBoxHunBan3.setGeometry(QRect(20, 150, 71, 22))
        self.cBoxHunBan3.setEditable(True)
        self.labHunBan3Pic = QLabel(self.groupBox_4)
        self.labHunBan3Pic.setObjectName(u"labHunBan3Pic")
        self.labHunBan3Pic.setGeometry(QRect(30, 180, 51, 51))
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(110, 130, 54, 16))
        self.label_11.setAlignment(Qt.AlignCenter)
        self.cBoxHunBan4 = QComboBox(self.groupBox_4)
        self.cBoxHunBan4.setObjectName(u"cBoxHunBan4")
        self.cBoxHunBan4.setGeometry(QRect(100, 150, 71, 22))
        self.cBoxHunBan4.setEditable(True)
        self.labHunBan4Pic = QLabel(self.groupBox_4)
        self.labHunBan4Pic.setObjectName(u"labHunBan4Pic")
        self.labHunBan4Pic.setGeometry(QRect(110, 180, 51, 51))
        self.pBtnGen = QPushButton(form)
        self.pBtnGen.setObjectName(u"pBtnGen")
        self.pBtnGen.setGeometry(QRect(860, 20, 101, 24))
        font3 = QFont()
        font3.setFamilies([u"Arial"])
        font3.setPointSize(10)
        font3.setBold(True)
        self.pBtnGen.setFont(font3)
        self.groupBox_5 = QGroupBox(form)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(30, 370, 391, 161))
        self.groupBox_5.setFont(font3)
        self.cBoxSurPick1 = QComboBox(self.groupBox_5)
        self.cBoxSurPick1.setObjectName(u"cBoxSurPick1")
        self.cBoxSurPick1.setGeometry(QRect(20, 50, 71, 22))
        self.cBoxSurPick1.setEditable(True)
        self.label_12 = QLabel(self.groupBox_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 30, 54, 16))
        self.label_12.setAlignment(Qt.AlignCenter)
        self.labSurPick1Pic = QLabel(self.groupBox_5)
        self.labSurPick1Pic.setObjectName(u"labSurPick1Pic")
        self.labSurPick1Pic.setGeometry(QRect(20, 80, 70, 70))
        self.label_13 = QLabel(self.groupBox_5)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(110, 30, 54, 16))
        self.label_13.setAlignment(Qt.AlignCenter)
        self.cBoxSurPick2 = QComboBox(self.groupBox_5)
        self.cBoxSurPick2.setObjectName(u"cBoxSurPick2")
        self.cBoxSurPick2.setGeometry(QRect(100, 50, 71, 22))
        self.cBoxSurPick2.setEditable(True)
        self.labSurPick2Pic = QLabel(self.groupBox_5)
        self.labSurPick2Pic.setObjectName(u"labSurPick2Pic")
        self.labSurPick2Pic.setGeometry(QRect(100, 80, 70, 70))
        self.label_14 = QLabel(self.groupBox_5)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(230, 30, 54, 16))
        self.label_14.setAlignment(Qt.AlignCenter)
        self.cBoxSurPick3 = QComboBox(self.groupBox_5)
        self.cBoxSurPick3.setObjectName(u"cBoxSurPick3")
        self.cBoxSurPick3.setGeometry(QRect(220, 50, 71, 22))
        self.cBoxSurPick3.setEditable(True)
        self.labSurPick3Pic = QLabel(self.groupBox_5)
        self.labSurPick3Pic.setObjectName(u"labSurPick3Pic")
        self.labSurPick3Pic.setGeometry(QRect(220, 80, 70, 70))
        self.label_15 = QLabel(self.groupBox_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(310, 30, 54, 16))
        self.label_15.setAlignment(Qt.AlignCenter)
        self.cBoxSurPick4 = QComboBox(self.groupBox_5)
        self.cBoxSurPick4.setObjectName(u"cBoxSurPick4")
        self.cBoxSurPick4.setGeometry(QRect(300, 50, 71, 22))
        self.cBoxSurPick4.setEditable(True)
        self.labSurPick4Pic = QLabel(self.groupBox_5)
        self.labSurPick4Pic.setObjectName(u"labSurPick4Pic")
        self.labSurPick4Pic.setGeometry(QRect(300, 80, 70, 70))
        self.groupBox_6 = QGroupBox(form)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(440, 370, 171, 161))
        self.groupBox_6.setFont(font3)
        self.cBoxHunPick = QComboBox(self.groupBox_6)
        self.cBoxHunPick.setObjectName(u"cBoxHunPick")
        self.cBoxHunPick.setGeometry(QRect(50, 50, 71, 22))
        self.cBoxHunPick.setEditable(True)
        self.label_16 = QLabel(self.groupBox_6)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(60, 30, 54, 16))
        self.label_16.setAlignment(Qt.AlignCenter)
        self.labHunPickPic = QLabel(self.groupBox_6)
        self.labHunPickPic.setObjectName(u"labHunPickPic")
        self.labHunPickPic.setGeometry(QRect(20, 80, 70, 70))
        self.pBtnRes = QPushButton(form)
        self.pBtnRes.setObjectName(u"pBtnRes")
        self.pBtnRes.setGeometry(QRect(860, 80, 101, 24))
        font4 = QFont()
        font4.setFamilies([u"Agency FB"])
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setUnderline(False)
        self.pBtnRes.setFont(font4)
        self.groupBox_7 = QGroupBox(form)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(620, 110, 341, 421))
        self.groupBox_7.setFont(font2)
        self.stackedWidget = QStackedWidget(self.groupBox_7)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(20, 270, 171, 121))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setFrameShape(QFrame.Panel)
        self.stackedWidget.setFrameShadow(QFrame.Raised)
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.splitter_4 = QSplitter(self.page_1)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setGeometry(QRect(20, 10, 131, 51))
        self.splitter_4.setOrientation(Qt.Vertical)
        self.label_20 = QLabel(self.splitter_4)
        self.label_20.setObjectName(u"label_20")
        self.splitter_4.addWidget(self.label_20)
        self.splitter_3 = QSplitter(self.splitter_4)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.b1_l_1 = QSpinBox(self.splitter_3)
        self.b1_l_1.setObjectName(u"b1_l_1")
        self.b1_l_1.setMaximum(5)
        self.splitter_3.addWidget(self.b1_l_1)
        self.label_19 = QLabel(self.splitter_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setFont(font3)
        self.splitter_3.addWidget(self.label_19)
        self.b1_r_1 = QSpinBox(self.splitter_3)
        self.b1_r_1.setObjectName(u"b1_r_1")
        self.b1_r_1.setMaximum(5)
        self.splitter_3.addWidget(self.b1_r_1)
        self.splitter_4.addWidget(self.splitter_3)
        self.splitter_13 = QSplitter(self.page_1)
        self.splitter_13.setObjectName(u"splitter_13")
        self.splitter_13.setGeometry(QRect(20, 80, 131, 26))
        self.splitter_13.setOrientation(Qt.Horizontal)
        self.b1_l_2 = QSpinBox(self.splitter_13)
        self.b1_l_2.setObjectName(u"b1_l_2")
        self.b1_l_2.setMaximum(5)
        self.splitter_13.addWidget(self.b1_l_2)
        self.label_29 = QLabel(self.splitter_13)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setFont(font3)
        self.splitter_13.addWidget(self.label_29)
        self.b1_r_2 = QSpinBox(self.splitter_13)
        self.b1_r_2.setObjectName(u"b1_r_2")
        self.b1_r_2.setMaximum(5)
        self.splitter_13.addWidget(self.b1_r_2)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.splitter_5 = QSplitter(self.page_2)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setGeometry(QRect(20, 10, 131, 51))
        self.splitter_5.setOrientation(Qt.Vertical)
        self.label_21 = QLabel(self.splitter_5)
        self.label_21.setObjectName(u"label_21")
        self.splitter_5.addWidget(self.label_21)
        self.splitter_6 = QSplitter(self.splitter_5)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setOrientation(Qt.Horizontal)
        self.b2_l_1 = QSpinBox(self.splitter_6)
        self.b2_l_1.setObjectName(u"b2_l_1")
        self.b2_l_1.setMaximum(5)
        self.splitter_6.addWidget(self.b2_l_1)
        self.label_22 = QLabel(self.splitter_6)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setFont(font3)
        self.splitter_6.addWidget(self.label_22)
        self.b2_r_1 = QSpinBox(self.splitter_6)
        self.b2_r_1.setObjectName(u"b2_r_1")
        self.b2_r_1.setMaximum(5)
        self.splitter_6.addWidget(self.b2_r_1)
        self.splitter_5.addWidget(self.splitter_6)
        self.splitter_14 = QSplitter(self.page_2)
        self.splitter_14.setObjectName(u"splitter_14")
        self.splitter_14.setGeometry(QRect(20, 80, 131, 26))
        self.splitter_14.setOrientation(Qt.Horizontal)
        self.b2_l_2 = QSpinBox(self.splitter_14)
        self.b2_l_2.setObjectName(u"b2_l_2")
        self.b2_l_2.setMaximum(5)
        self.splitter_14.addWidget(self.b2_l_2)
        self.label_30 = QLabel(self.splitter_14)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setFont(font3)
        self.splitter_14.addWidget(self.label_30)
        self.b2_r_2 = QSpinBox(self.splitter_14)
        self.b2_r_2.setObjectName(u"b2_r_2")
        self.b2_r_2.setMaximum(5)
        self.splitter_14.addWidget(self.b2_r_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.splitter_7 = QSplitter(self.page_3)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setGeometry(QRect(20, 10, 131, 51))
        self.splitter_7.setOrientation(Qt.Vertical)
        self.label_23 = QLabel(self.splitter_7)
        self.label_23.setObjectName(u"label_23")
        self.splitter_7.addWidget(self.label_23)
        self.splitter_8 = QSplitter(self.splitter_7)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setOrientation(Qt.Horizontal)
        self.b3_l_1 = QSpinBox(self.splitter_8)
        self.b3_l_1.setObjectName(u"b3_l_1")
        self.b3_l_1.setMaximum(5)
        self.splitter_8.addWidget(self.b3_l_1)
        self.label_24 = QLabel(self.splitter_8)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setFont(font3)
        self.splitter_8.addWidget(self.label_24)
        self.b3_r_1 = QSpinBox(self.splitter_8)
        self.b3_r_1.setObjectName(u"b3_r_1")
        self.b3_r_1.setMaximum(5)
        self.splitter_8.addWidget(self.b3_r_1)
        self.splitter_7.addWidget(self.splitter_8)
        self.splitter_15 = QSplitter(self.page_3)
        self.splitter_15.setObjectName(u"splitter_15")
        self.splitter_15.setGeometry(QRect(20, 80, 131, 26))
        self.splitter_15.setOrientation(Qt.Horizontal)
        self.b3_l_2 = QSpinBox(self.splitter_15)
        self.b3_l_2.setObjectName(u"b3_l_2")
        self.b3_l_2.setMaximum(5)
        self.splitter_15.addWidget(self.b3_l_2)
        self.label_31 = QLabel(self.splitter_15)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setFont(font3)
        self.splitter_15.addWidget(self.label_31)
        self.b3_r_2 = QSpinBox(self.splitter_15)
        self.b3_r_2.setObjectName(u"b3_r_2")
        self.b3_r_2.setMaximum(5)
        self.splitter_15.addWidget(self.b3_r_2)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.splitter_9 = QSplitter(self.page)
        self.splitter_9.setObjectName(u"splitter_9")
        self.splitter_9.setGeometry(QRect(20, 10, 131, 51))
        self.splitter_9.setOrientation(Qt.Vertical)
        self.label_25 = QLabel(self.splitter_9)
        self.label_25.setObjectName(u"label_25")
        self.splitter_9.addWidget(self.label_25)
        self.splitter_10 = QSplitter(self.splitter_9)
        self.splitter_10.setObjectName(u"splitter_10")
        self.splitter_10.setOrientation(Qt.Horizontal)
        self.b4_l_1 = QSpinBox(self.splitter_10)
        self.b4_l_1.setObjectName(u"b4_l_1")
        self.b4_l_1.setMaximum(5)
        self.splitter_10.addWidget(self.b4_l_1)
        self.label_26 = QLabel(self.splitter_10)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setFont(font3)
        self.splitter_10.addWidget(self.label_26)
        self.b4_r_1 = QSpinBox(self.splitter_10)
        self.b4_r_1.setObjectName(u"b4_r_1")
        self.b4_r_1.setMaximum(5)
        self.splitter_10.addWidget(self.b4_r_1)
        self.splitter_9.addWidget(self.splitter_10)
        self.splitter_16 = QSplitter(self.page)
        self.splitter_16.setObjectName(u"splitter_16")
        self.splitter_16.setGeometry(QRect(20, 80, 131, 26))
        self.splitter_16.setOrientation(Qt.Horizontal)
        self.b4_l_2 = QSpinBox(self.splitter_16)
        self.b4_l_2.setObjectName(u"b4_l_2")
        self.b4_l_2.setMaximum(5)
        self.splitter_16.addWidget(self.b4_l_2)
        self.label_32 = QLabel(self.splitter_16)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setFont(font3)
        self.splitter_16.addWidget(self.label_32)
        self.b4_r_2 = QSpinBox(self.splitter_16)
        self.b4_r_2.setObjectName(u"b4_r_2")
        self.b4_r_2.setMaximum(5)
        self.splitter_16.addWidget(self.b4_r_2)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.splitter_11 = QSplitter(self.page_4)
        self.splitter_11.setObjectName(u"splitter_11")
        self.splitter_11.setGeometry(QRect(20, 10, 131, 51))
        self.splitter_11.setOrientation(Qt.Vertical)
        self.label_27 = QLabel(self.splitter_11)
        self.label_27.setObjectName(u"label_27")
        self.splitter_11.addWidget(self.label_27)
        self.splitter_12 = QSplitter(self.splitter_11)
        self.splitter_12.setObjectName(u"splitter_12")
        self.splitter_12.setOrientation(Qt.Horizontal)
        self.b5_l_1 = QSpinBox(self.splitter_12)
        self.b5_l_1.setObjectName(u"b5_l_1")
        self.b5_l_1.setMaximum(5)
        self.splitter_12.addWidget(self.b5_l_1)
        self.label_28 = QLabel(self.splitter_12)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setFont(font3)
        self.splitter_12.addWidget(self.label_28)
        self.b5_r_1 = QSpinBox(self.splitter_12)
        self.b5_r_1.setObjectName(u"b5_r_1")
        self.b5_r_1.setMaximum(5)
        self.splitter_12.addWidget(self.b5_r_1)
        self.splitter_11.addWidget(self.splitter_12)
        self.splitter_17 = QSplitter(self.page_4)
        self.splitter_17.setObjectName(u"splitter_17")
        self.splitter_17.setGeometry(QRect(20, 80, 131, 26))
        self.splitter_17.setOrientation(Qt.Horizontal)
        self.b5_l_2 = QSpinBox(self.splitter_17)
        self.b5_l_2.setObjectName(u"b5_l_2")
        self.b5_l_2.setMaximum(5)
        self.splitter_17.addWidget(self.b5_l_2)
        self.label_33 = QLabel(self.splitter_17)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setFont(font3)
        self.splitter_17.addWidget(self.label_33)
        self.b5_r_2 = QSpinBox(self.splitter_17)
        self.b5_r_2.setObjectName(u"b5_r_2")
        self.b5_r_2.setMaximum(5)
        self.splitter_17.addWidget(self.b5_r_2)
        self.stackedWidget.addWidget(self.page_4)
        self.team1logo = QPushButton(self.groupBox_7)
        self.team1logo.setObjectName(u"team1logo")
        self.team1logo.setGeometry(QRect(20, 50, 121, 21))
        self.team2logo = QPushButton(self.groupBox_7)
        self.team2logo.setObjectName(u"team2logo")
        self.team2logo.setGeometry(QRect(180, 50, 121, 21))
        self.splitter_2 = QSplitter(self.groupBox_7)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(20, 20, 281, 19))
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.team1 = QLineEdit(self.splitter_2)
        self.team1.setObjectName(u"team1")
        font5 = QFont()
        font5.setFamilies([u"\u534e\u5eb7POP"])
        font5.setPointSize(10)
        font5.setBold(False)
        self.team1.setFont(font5)
        self.splitter_2.addWidget(self.team1)
        self.label_18 = QLabel(self.splitter_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setFont(font3)
        self.splitter_2.addWidget(self.label_18)
        self.team2 = QLineEdit(self.splitter_2)
        self.team2.setObjectName(u"team2")
        self.team2.setFont(font5)
        self.splitter_2.addWidget(self.team2)
        self.next = QPushButton(self.groupBox_7)
        self.next.setObjectName(u"next")
        self.next.setGeometry(QRect(210, 300, 75, 24))
        self.previous = QPushButton(self.groupBox_7)
        self.previous.setObjectName(u"previous")
        self.previous.setGeometry(QRect(210, 270, 75, 24))
        self.splitter = QSplitter(self.groupBox_7)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(30, 230, 261, 21))
        self.splitter.setOrientation(Qt.Horizontal)
        self.label_35 = QLabel(self.splitter)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setFont(font3)
        self.splitter.addWidget(self.label_35)
        self.mode3 = QRadioButton(self.splitter)
        self.mode3.setObjectName(u"mode3")
        font6 = QFont()
        font6.setFamilies([u"Segoe UI"])
        font6.setPointSize(10)
        font6.setBold(False)
        self.mode3.setFont(font6)
        self.mode3.setChecked(False)
        self.splitter.addWidget(self.mode3)
        self.mode5 = QRadioButton(self.splitter)
        self.mode5.setObjectName(u"mode5")
        self.mode5.setChecked(True)
        self.splitter.addWidget(self.mode5)
        self.team1pic = QLabel(self.groupBox_7)
        self.team1pic.setObjectName(u"team1pic")
        self.team1pic.setGeometry(QRect(30, 90, 101, 101))
        self.team2pic = QLabel(self.groupBox_7)
        self.team2pic.setObjectName(u"team2pic")
        self.team2pic.setGeometry(QRect(190, 90, 101, 101))
        self.pointGen = QPushButton(form)
        self.pointGen.setObjectName(u"pointGen")
        self.pointGen.setGeometry(QRect(860, 50, 101, 21))
        self.pointGen.setFont(font3)
#if QT_CONFIG(shortcut)
        self.label_2.setBuddy(self.lEdtHun)
        self.label.setBuddy(self.lEdtSur)
        self.label_3.setBuddy(self.cBoxSurBan1)
        self.label_4.setBuddy(self.cBoxSurBan2)
        self.label_5.setBuddy(self.cBoxSurBan3)
        self.label_6.setBuddy(self.cBoxSurBan4)
        self.label_7.setBuddy(self.cBoxSurBan5)
        self.label_17.setBuddy(self.cBoxSurBan6)
        self.label_34.setBuddy(self.cBoxSurBan6)
        self.label_8.setBuddy(self.cBoxHunBan1)
        self.label_9.setBuddy(self.cBoxHunBan2)
        self.label_10.setBuddy(self.cBoxHunBan3)
        self.label_11.setBuddy(self.cBoxHunBan4)
        self.label_12.setBuddy(self.cBoxSurPick1)
        self.label_13.setBuddy(self.cBoxSurPick2)
        self.label_14.setBuddy(self.cBoxSurPick3)
        self.label_15.setBuddy(self.cBoxSurPick4)
        self.label_16.setBuddy(self.cBoxHunPick)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.lEdtSur, self.pButSwapTeam)
        QWidget.setTabOrder(self.pButSwapTeam, self.lEdtHun)
        QWidget.setTabOrder(self.lEdtHun, self.cBoxMap)
        QWidget.setTabOrder(self.cBoxMap, self.pBtnGen)
        QWidget.setTabOrder(self.pBtnGen, self.pBtnRes)
        QWidget.setTabOrder(self.pBtnRes, self.cBoxSurBan1)
        QWidget.setTabOrder(self.cBoxSurBan1, self.cBoxSurBan2)
        QWidget.setTabOrder(self.cBoxSurBan2, self.cBoxSurBan3)
        QWidget.setTabOrder(self.cBoxSurBan3, self.cBoxSurBan4)
        QWidget.setTabOrder(self.cBoxSurBan4, self.cBoxSurBan5)
        QWidget.setTabOrder(self.cBoxSurBan5, self.cBoxSurBan6)
        QWidget.setTabOrder(self.cBoxSurBan6, self.cBoxHunBan1)
        QWidget.setTabOrder(self.cBoxHunBan1, self.cBoxHunBan2)
        QWidget.setTabOrder(self.cBoxHunBan2, self.cBoxHunBan3)
        QWidget.setTabOrder(self.cBoxHunBan3, self.cBoxHunBan4)
        QWidget.setTabOrder(self.cBoxHunBan4, self.cBoxSurPick1)
        QWidget.setTabOrder(self.cBoxSurPick1, self.cBoxSurPick2)
        QWidget.setTabOrder(self.cBoxSurPick2, self.cBoxSurPick3)
        QWidget.setTabOrder(self.cBoxSurPick3, self.cBoxSurPick4)
        QWidget.setTabOrder(self.cBoxSurPick4, self.cBoxHunPick)

        self.retranslateUi(form)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(form)
    # setupUi

    def retranslateUi(self, form):
        form.setWindowTitle(QCoreApplication.translate("form", u"\u7b2c\u4e94\u4eba\u683cbp\u7cfb\u7edf-\u540e\u53f0", None))
        self.groupBox.setTitle(QCoreApplication.translate("form", u"\u961f\u4f0d\u4fe1\u606f", None))
        self.label_2.setText(QCoreApplication.translate("form", u"\u76d1\u7ba1\u8005\u961f\u4f0d", None))
        self.label.setText(QCoreApplication.translate("form", u"\u6c42\u751f\u8005\u961f\u4f0d", None))
        self.pButSwapTeam.setText(QCoreApplication.translate("form", u"\u4ea4\u6362\u4f4d\u7f6e", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("form", u"\u9009\u56fe", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("form", u"ban\u6c42\u751f\u8005", None))
        self.label_3.setText(QCoreApplication.translate("form", u"ban1", None))
        self.labSurBan1Pic.setText("")
        self.label_4.setText(QCoreApplication.translate("form", u"ban2", None))
        self.labSurBan2Pic.setText("")
        self.label_5.setText(QCoreApplication.translate("form", u"ban3", None))
        self.labSurBan3Pic.setText("")
        self.label_6.setText(QCoreApplication.translate("form", u"ban4", None))
        self.labSurBan4Pic.setText("")
        self.label_7.setText(QCoreApplication.translate("form", u"ban5", None))
        self.labSurBan5Pic.setText("")
        self.label_17.setText(QCoreApplication.translate("form", u"ban6", None))
        self.labSurBan6Pic.setText("")
        self.label_34.setText(QCoreApplication.translate("form", u"ban7", None))
        self.labSurBan7Pic.setText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("form", u"ban\u76d1\u7ba1\u8005", None))
        self.label_8.setText(QCoreApplication.translate("form", u"ban1", None))
        self.labHunBan1Pic.setText("")
        self.label_9.setText(QCoreApplication.translate("form", u"ban2", None))
        self.labHunBan2Pic.setText("")
        self.label_10.setText(QCoreApplication.translate("form", u"ban3", None))
        self.labHunBan3Pic.setText("")
        self.label_11.setText(QCoreApplication.translate("form", u"ban4", None))
        self.labHunBan4Pic.setText("")
        self.pBtnGen.setText(QCoreApplication.translate("form", u"\u751f\u6210bp\u754c\u9762", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("form", u"pick\u6c42\u751f\u8005", None))
        self.label_12.setText(QCoreApplication.translate("form", u"pick1", None))
        self.labSurPick1Pic.setText("")
        self.label_13.setText(QCoreApplication.translate("form", u"pick2", None))
        self.labSurPick2Pic.setText("")
        self.label_14.setText(QCoreApplication.translate("form", u"pick3", None))
        self.labSurPick3Pic.setText("")
        self.label_15.setText(QCoreApplication.translate("form", u"pick4", None))
        self.labSurPick4Pic.setText("")
        self.groupBox_6.setTitle(QCoreApplication.translate("form", u"pick\u76d1\u7ba1\u8005", None))
        self.label_16.setText(QCoreApplication.translate("form", u"pick", None))
        self.labHunPickPic.setText("")
        self.pBtnRes.setText(QCoreApplication.translate("form", u"\u91cd\u7f6e", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("form", u"\u6bd4\u5206", None))
        self.label_20.setText(QCoreApplication.translate("form", u"bo1", None))
        self.label_19.setText(QCoreApplication.translate("form", u":", None))
        self.label_29.setText(QCoreApplication.translate("form", u":", None))
        self.label_21.setText(QCoreApplication.translate("form", u"bo2", None))
        self.label_22.setText(QCoreApplication.translate("form", u":", None))
        self.label_30.setText(QCoreApplication.translate("form", u":", None))
        self.label_23.setText(QCoreApplication.translate("form", u"bo3", None))
        self.label_24.setText(QCoreApplication.translate("form", u":", None))
        self.label_31.setText(QCoreApplication.translate("form", u":", None))
        self.label_25.setText(QCoreApplication.translate("form", u"bo4", None))
        self.label_26.setText(QCoreApplication.translate("form", u":", None))
        self.label_32.setText(QCoreApplication.translate("form", u":", None))
        self.label_27.setText(QCoreApplication.translate("form", u"bo5", None))
        self.label_28.setText(QCoreApplication.translate("form", u":", None))
        self.label_33.setText(QCoreApplication.translate("form", u":", None))
        self.team1logo.setText(QCoreApplication.translate("form", u"\u5bfc\u5165team1\u961f\u5fbd", None))
        self.team2logo.setText(QCoreApplication.translate("form", u"\u5bfc\u5165team2\u961f\u5fbd", None))
        self.label_18.setText(QCoreApplication.translate("form", u"vs", None))
        self.next.setText(QCoreApplication.translate("form", u"\u4e0b\u4e00\u5c40", None))
        self.previous.setText(QCoreApplication.translate("form", u"\u4e0a\u4e00\u5c40", None))
        self.label_35.setText(QCoreApplication.translate("form", u"\u6a21\u5f0f\u9009\u62e9\uff1a", None))
        self.mode3.setText(QCoreApplication.translate("form", u"bo3", None))
        self.mode5.setText(QCoreApplication.translate("form", u"bo5", None))
        self.team1pic.setText("")
        self.team2pic.setText("")
        self.pointGen.setText(QCoreApplication.translate("form", u"\u751f\u6210\u6bd4\u5206\u9875\u9762", None))
    # retranslateUi

