# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'WinPoint.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1440, 809)
        Form.setMinimumSize(QSize(1440, 809))
        Form.setMaximumSize(QSize(1440, 809))
        self.bg = QLabel(Form)
        self.bg.setObjectName(u"bg")
        self.bg.setGeometry(QRect(0, 0, 1440, 809))
        self.bg.setAutoFillBackground(False)
        self.bg.setPixmap(QPixmap(u"../pic/pointbg.png"))
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QRect(360, 510, 131, 41))
        font = QFont()
        font.setFamilies([u"Segoe Print"])
        font.setPointSize(23)
        font.setBold(True)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.g3 = QLabel(Form)
        self.g3.setObjectName(u"g3")
        self.g3.setGeometry(QRect(510, 590, 181, 31))
        font1 = QFont()
        font1.setFamilies([u"Impact"])
        font1.setPointSize(23)
        self.g3.setFont(font1)
        self.g3.setAlignment(Qt.AlignCenter)
        self.team2pic = QLabel(Form)
        self.team2pic.setObjectName(u"team2pic")
        self.team2pic.setGeometry(QRect(1050, 120, 181, 171))
        self.team1pic = QLabel(Form)
        self.team1pic.setObjectName(u"team1pic")
        self.team1pic.setGeometry(QRect(190, 110, 181, 171))
        self.g1 = QLabel(Form)
        self.g1.setObjectName(u"g1")
        self.g1.setGeometry(QRect(510, 450, 181, 31))
        self.g1.setFont(font1)
        self.g1.setAlignment(Qt.AlignCenter)
        self.label_1 = QLabel(Form)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setEnabled(True)
        self.label_1.setGeometry(QRect(360, 440, 131, 41))
        self.label_1.setFont(font)
        self.g4 = QLabel(Form)
        self.g4.setObjectName(u"g4")
        self.g4.setGeometry(QRect(850, 450, 181, 31))
        self.g4.setFont(font1)
        self.g4.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QRect(710, 440, 131, 41))
        self.label_4.setFont(font)
        self.t2_name = QLabel(Form)
        self.t2_name.setObjectName(u"t2_name")
        self.t2_name.setGeometry(QRect(940, 300, 411, 71))
        font2 = QFont()
        font2.setFamilies([u"\u534e\u5eb7POP"])
        font2.setPointSize(24)
        font2.setBold(True)
        self.t2_name.setFont(font2)
        self.t2_name.setAlignment(Qt.AlignCenter)
        self.g2 = QLabel(Form)
        self.g2.setObjectName(u"g2")
        self.g2.setGeometry(QRect(510, 520, 181, 31))
        self.g2.setFont(font1)
        self.g2.setAlignment(Qt.AlignCenter)
        self.g5 = QLabel(Form)
        self.g5.setObjectName(u"g5")
        self.g5.setGeometry(QRect(850, 520, 181, 31))
        self.g5.setFont(font1)
        self.g5.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QRect(360, 580, 131, 41))
        self.label_3.setFont(font)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QRect(710, 510, 131, 41))
        self.label_5.setFont(font)
        self.t1_name = QLabel(Form)
        self.t1_name.setObjectName(u"t1_name")
        self.t1_name.setGeometry(QRect(80, 300, 411, 71))
        self.t1_name.setFont(font2)
        self.t1_name.setAlignment(Qt.AlignCenter)
        self.wdl1 = QLabel(Form)
        self.wdl1.setObjectName(u"wdl1")
        self.wdl1.setGeometry(QRect(440, 110, 191, 51))
        font3 = QFont()
        font3.setFamilies([u"\u534e\u5eb7POP"])
        font3.setPointSize(23)
        font3.setBold(True)
        self.wdl1.setFont(font3)
        self.wdl1.setAlignment(Qt.AlignCenter)
        self.wdl2 = QLabel(Form)
        self.wdl2.setObjectName(u"wdl2")
        self.wdl2.setGeometry(QRect(860, 110, 191, 51))
        self.wdl2.setFont(font3)
        self.wdl2.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u7b2c\u4e94\u4eba\u683cbp\u7cfb\u7edf-\u6bd4\u5206", None))
        self.bg.setText("")
        self.label_2.setText(QCoreApplication.translate("Form", u"GAME2", None))
        self.g3.setText(QCoreApplication.translate("Form", u"- : -", None))
        self.team2pic.setText("")
        self.team1pic.setText("")
        self.g1.setText(QCoreApplication.translate("Form", u"- : -", None))
        self.label_1.setText(QCoreApplication.translate("Form", u"GAME1", None))
        self.g4.setText(QCoreApplication.translate("Form", u"- : -", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"GAME4", None))
        self.t2_name.setText(QCoreApplication.translate("Form", u"\u961f\u4f0d\u4e8c", None))
        self.g2.setText(QCoreApplication.translate("Form", u"- : -", None))
        self.g5.setText(QCoreApplication.translate("Form", u"- : -", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"GAME3", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"GAME5", None))
        self.t1_name.setText(QCoreApplication.translate("Form", u"\u961f\u4f0d\u4e00", None))
        self.wdl1.setText(QCoreApplication.translate("Form", u"W   D   L", None))
        self.wdl2.setText(QCoreApplication.translate("Form", u"W   D   L", None))
    # retranslateUi

