# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'WinFg.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1440, 810)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAutoFillBackground(False)
        self.labSurPick1Pic = QLabel(Form)
        self.labSurPick1Pic.setObjectName(u"labSurPick1Pic")
        self.labSurPick1Pic.setGeometry(QRect(144, 242, 151, 151))
        self.labSurPick1Pic.setAutoFillBackground(False)
        self.labSurPick1Pic.setStyleSheet(u"")
        self.labSurPick1Pic.setAlignment(Qt.AlignCenter)
        self.labSurPick2Pic = QLabel(Form)
        self.labSurPick2Pic.setObjectName(u"labSurPick2Pic")
        self.labSurPick2Pic.setGeometry(QRect(499, 244, 151, 151))
        self.labSurPick2Pic.setAlignment(Qt.AlignCenter)
        self.labSurPick4Pic = QLabel(Form)
        self.labSurPick4Pic.setObjectName(u"labSurPick4Pic")
        self.labSurPick4Pic.setGeometry(QRect(499, 458, 151, 151))
        self.labSurPick4Pic.setAlignment(Qt.AlignCenter)
        self.labSurPick3Pic = QLabel(Form)
        self.labSurPick3Pic.setObjectName(u"labSurPick3Pic")
        self.labSurPick3Pic.setGeometry(QRect(144, 459, 151, 151))
        self.labSurPick3Pic.setAlignment(Qt.AlignCenter)
        self.labHunPickPic = QLabel(Form)
        self.labHunPickPic.setObjectName(u"labHunPickPic")
        self.labHunPickPic.setGeometry(QRect(993, 180, 351, 351))
        self.labHunPickPic.setStyleSheet(u"")
        self.labHunPickPic.setAlignment(Qt.AlignCenter)
        self.labHunBan1Pic = QLabel(Form)
        self.labHunBan1Pic.setObjectName(u"labHunBan1Pic")
        self.labHunBan1Pic.setGeometry(QRect(160, 130, 91, 91))
        self.labHunBan1Pic.setAutoFillBackground(False)
        self.labHunBan1Pic.setStyleSheet(u"")
        self.labHunBan1Pic.setAlignment(Qt.AlignCenter)
        self.labHunBan2Pic = QLabel(Form)
        self.labHunBan2Pic.setObjectName(u"labHunBan2Pic")
        self.labHunBan2Pic.setGeometry(QRect(330, 130, 91, 91))
        self.labHunBan2Pic.setAutoFillBackground(False)
        self.labHunBan2Pic.setStyleSheet(u"")
        self.labHunBan2Pic.setAlignment(Qt.AlignCenter)
        self.labHunBan3Pic = QLabel(Form)
        self.labHunBan3Pic.setObjectName(u"labHunBan3Pic")
        self.labHunBan3Pic.setGeometry(QRect(500, 130, 91, 91))
        self.labHunBan3Pic.setAutoFillBackground(False)
        self.labHunBan3Pic.setStyleSheet(u"")
        self.labHunBan3Pic.setAlignment(Qt.AlignCenter)
        self.labHunBan4Pic = QLabel(Form)
        self.labHunBan4Pic.setObjectName(u"labHunBan4Pic")
        self.labHunBan4Pic.setGeometry(QRect(680, 130, 91, 91))
        self.labHunBan4Pic.setAutoFillBackground(False)
        self.labHunBan4Pic.setStyleSheet(u"")
        self.labHunBan4Pic.setAlignment(Qt.AlignCenter)
        self.labSurBan1Pic = QLabel(Form)
        self.labSurBan1Pic.setObjectName(u"labSurBan1Pic")
        self.labSurBan1Pic.setGeometry(QRect(974, 596, 81, 81))
        self.labSurBan1Pic.setAutoFillBackground(False)
        self.labSurBan1Pic.setStyleSheet(u"")
        self.labSurBan1Pic.setAlignment(Qt.AlignCenter)
        self.labSurBan5Pic = QLabel(Form)
        self.labSurBan5Pic.setObjectName(u"labSurBan5Pic")
        self.labSurBan5Pic.setGeometry(QRect(974, 710, 81, 81))
        self.labSurBan5Pic.setAutoFillBackground(False)
        self.labSurBan5Pic.setStyleSheet(u"")
        self.labSurBan5Pic.setAlignment(Qt.AlignCenter)
        self.labSurBan6Pic = QLabel(Form)
        self.labSurBan6Pic.setObjectName(u"labSurBan6Pic")
        self.labSurBan6Pic.setGeometry(QRect(1090, 710, 81, 81))
        self.labSurBan6Pic.setAutoFillBackground(False)
        self.labSurBan6Pic.setStyleSheet(u"")
        self.labSurBan6Pic.setAlignment(Qt.AlignCenter)
        self.labSurBan7Pic = QLabel(Form)
        self.labSurBan7Pic.setObjectName(u"labSurBan7Pic")
        self.labSurBan7Pic.setGeometry(QRect(1203, 710, 81, 81))
        self.labSurBan7Pic.setAutoFillBackground(False)
        self.labSurBan7Pic.setStyleSheet(u"")
        self.labSurBan7Pic.setAlignment(Qt.AlignCenter)
        self.labSurBan8Pic = QLabel(Form)
        self.labSurBan8Pic.setObjectName(u"labSurBan8Pic")
        self.labSurBan8Pic.setGeometry(QRect(1317, 710, 81, 81))
        self.labSurBan8Pic.setAutoFillBackground(False)
        self.labSurBan8Pic.setStyleSheet(u"")
        self.labSurBan8Pic.setAlignment(Qt.AlignCenter)
        self.labSurTeam = QLabel(Form)
        self.labSurTeam.setObjectName(u"labSurTeam")
        self.labSurTeam.setGeometry(QRect(30, 20, 231, 71))
        font = QFont()
        font.setFamilies([u"\u534e\u5eb7POP"])
        font.setPointSize(25)
        self.labSurTeam.setFont(font)
        self.labSurTeam.setStyleSheet(u"color: rgb(240, 240, 240);")
        self.labSurTeam.setAlignment(Qt.AlignCenter)
        self.labHunTeam = QLabel(Form)
        self.labHunTeam.setObjectName(u"labHunTeam")
        self.labHunTeam.setGeometry(QRect(1170, 20, 231, 71))
        self.labHunTeam.setFont(font)
        self.labHunTeam.setStyleSheet(u"color: rgb(240, 240, 240);")
        self.labHunTeam.setAlignment(Qt.AlignCenter)
        self.labSurPick1 = QLabel(Form)
        self.labSurPick1.setObjectName(u"labSurPick1")
        self.labSurPick1.setGeometry(QRect(125, 399, 191, 41))
        font1 = QFont()
        font1.setFamilies([u"\u534e\u5eb7POP"])
        font1.setPointSize(20)
        self.labSurPick1.setFont(font1)
        self.labSurPick1.setAlignment(Qt.AlignCenter)
        self.labSurPick2 = QLabel(Form)
        self.labSurPick2.setObjectName(u"labSurPick2")
        self.labSurPick2.setGeometry(QRect(480, 402, 191, 41))
        self.labSurPick2.setFont(font1)
        self.labSurPick2.setAlignment(Qt.AlignCenter)
        self.labSurPick3 = QLabel(Form)
        self.labSurPick3.setObjectName(u"labSurPick3")
        self.labSurPick3.setGeometry(QRect(120, 620, 191, 41))
        self.labSurPick3.setFont(font1)
        self.labSurPick3.setAlignment(Qt.AlignCenter)
        self.labSurPick4 = QLabel(Form)
        self.labSurPick4.setObjectName(u"labSurPick4")
        self.labSurPick4.setGeometry(QRect(470, 620, 201, 41))
        self.labSurPick4.setFont(font1)
        self.labSurPick4.setAlignment(Qt.AlignCenter)
        self.labHunPick = QLabel(Form)
        self.labHunPick.setObjectName(u"labHunPick")
        self.labHunPick.setGeometry(QRect(1090, 550, 171, 41))
        self.labHunPick.setFont(font1)
        self.labHunPick.setAlignment(Qt.AlignCenter)
        self.labBg = QLabel(Form)
        self.labBg.setObjectName(u"labBg")
        self.labBg.setGeometry(QRect(0, 0, 1440, 810))
        self.labBg.setPixmap(QPixmap(u"../pic/background.png"))
        self.labSurBan4Pic = QLabel(Form)
        self.labSurBan4Pic.setObjectName(u"labSurBan4Pic")
        self.labSurBan4Pic.setGeometry(QRect(1315, 596, 81, 81))
        self.labSurBan4Pic.setAutoFillBackground(False)
        self.labSurBan4Pic.setStyleSheet(u"")
        self.labSurBan4Pic.setAlignment(Qt.AlignCenter)
        self.labMapPic = QLabel(Form)
        self.labMapPic.setObjectName(u"labMapPic")
        self.labMapPic.setGeometry(QRect(530, -20, 361, 131))
        self.labMapPic.setAlignment(Qt.AlignCenter)
        self.labMap = QLabel(Form)
        self.labMap.setObjectName(u"labMap")
        self.labMap.setGeometry(QRect(610, 80, 211, 41))
        self.labMap.setFont(font1)
        self.labMap.setStyleSheet(u"color: rgb(240, 240, 240);")
        self.labMap.setAlignment(Qt.AlignCenter)
        self.labSurBan2Pic = QLabel(Form)
        self.labSurBan2Pic.setObjectName(u"labSurBan2Pic")
        self.labSurBan2Pic.setGeometry(QRect(1090, 600, 81, 81))
        self.labSurBan2Pic.setAutoFillBackground(False)
        self.labSurBan2Pic.setStyleSheet(u"")
        self.labSurBan2Pic.setAlignment(Qt.AlignCenter)
        self.labSurBan3Pic = QLabel(Form)
        self.labSurBan3Pic.setObjectName(u"labSurBan3Pic")
        self.labSurBan3Pic.setGeometry(QRect(1200, 600, 81, 81))
        self.labSurBan3Pic.setAutoFillBackground(False)
        self.labSurBan3Pic.setStyleSheet(u"")
        self.labSurBan3Pic.setAlignment(Qt.AlignCenter)
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(160, 130, 91, 91))
        self.label.setPixmap(QPixmap(u"./pic/ban.png"))
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(330, 130, 91, 91))
        self.label_2.setPixmap(QPixmap(u"./pic/ban.png"))
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(500, 130, 91, 91))
        self.label_3.setPixmap(QPixmap(u"./pic/ban.png"))
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(680, 130, 91, 91))
        self.label_4.setPixmap(QPixmap(u"./pic/ban.png"))
        self.labBg.raise_()
        self.labSurPick1Pic.raise_()
        self.labSurPick2Pic.raise_()
        self.labSurPick4Pic.raise_()
        self.labSurPick3Pic.raise_()
        self.labHunBan1Pic.raise_()
        self.labHunBan2Pic.raise_()
        self.labHunBan3Pic.raise_()
        self.labSurBan1Pic.raise_()
        self.labSurBan5Pic.raise_()
        self.labSurBan6Pic.raise_()
        self.labSurBan7Pic.raise_()
        self.labSurBan8Pic.raise_()
        self.labSurTeam.raise_()
        self.labHunTeam.raise_()
        self.labSurPick1.raise_()
        self.labSurPick2.raise_()
        self.labSurPick3.raise_()
        self.labSurPick4.raise_()
        self.labHunPick.raise_()
        self.labSurBan4Pic.raise_()
        self.labMapPic.raise_()
        self.labHunBan4Pic.raise_()
        self.labMap.raise_()
        self.labHunPickPic.raise_()
        self.labSurBan2Pic.raise_()
        self.labSurBan3Pic.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u7b2c\u4e94\u4eba\u683cbp\u754c\u9762", None))
        self.labSurPick1Pic.setText("")
        self.labSurPick2Pic.setText("")
        self.labSurPick4Pic.setText("")
        self.labSurPick3Pic.setText("")
        self.labHunPickPic.setText("")
        self.labHunBan1Pic.setText("")
        self.labHunBan2Pic.setText("")
        self.labHunBan3Pic.setText("")
        self.labHunBan4Pic.setText("")
        self.labSurBan1Pic.setText("")
        self.labSurBan5Pic.setText("")
        self.labSurBan6Pic.setText("")
        self.labSurBan7Pic.setText("")
        self.labSurBan8Pic.setText("")
        self.labSurTeam.setText("")
        self.labHunTeam.setText("")
        self.labSurPick1.setText("")
        self.labSurPick2.setText("")
        self.labSurPick3.setText("")
        self.labSurPick4.setText("")
        self.labHunPick.setText("")
        self.labBg.setText("")
        self.labSurBan4Pic.setText("")
        self.labMapPic.setText("")
        self.labMap.setText("")
        self.labSurBan2Pic.setText("")
        self.labSurBan3Pic.setText("")
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.label_4.setText("")
    # retranslateUi

